import type {Metadata} from "next"
import {Inter} from "next/font/google"
import "./globals.sass"
import Navigation from "@/components/base/Navigation/Navigation"
import {Toaster} from "react-hot-toast"
import {ReactNode} from "react"
import {UserContextEntity, UserProvider} from "@/context/UserContext"
import {decodeToken} from "@/utils/jwtTokenControl/jwtTokenControl"

const inter = Inter({subsets: ["latin"]})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    const decoded = await decodeToken()

    const user = decoded ? decoded.payload as unknown as UserContextEntity : null

    return (
        <html lang="en">
            <body className={inter.className}>
                <UserProvider user={user}>
                    <Navigation/>
                    {children}
                    <Toaster/>
                </UserProvider>
            </body>
        </html>
    )
}
